# Generated by Django 5.0.6 on 2024-05-20 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tvdisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
            ],
            options={
                'verbose_name': 'clock',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='HtmlContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'HTML page',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='IframeContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
                ('source', models.URLField(help_text='The URL of the content item.')),
            ],
            options={
                'verbose_name': 'iFrame',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='ImageContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
            ],
            options={
                'verbose_name': 'image',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='ImageListContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
            ],
            options={
                'verbose_name': 'image list',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='VideoContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
                ('video', models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('muted', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'video file',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='YoutubeContentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvdisplay.contentitem')),
                ('video_id', models.CharField(help_text='YouTube video ID from after ?v= in URL', max_length=30)),
            ],
            options={
                'verbose_name': 'YouTube video',
            },
            bases=('tvdisplay.contentitem',),
        ),
        migrations.CreateModel(
            name='ImageListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_list_images')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_items.imagelistcontentitem')),
            ],
        ),
    ]
