# Generated by Django 5.0.6 on 2024-05-20 14:54

import django.core.validators
import infokyllti.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelistitem',
            name='image',
            field=models.ImageField(upload_to='image_list_images'),
        ),
        migrations.AlterField(
            model_name='videocontentitem',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]