# Generated by Django 5.0.6 on 2024-05-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_items', '0003_pdfcontentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelistcontentitem',
            name='slide_display_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Number of seconds to display each slide.'),
        ),
        migrations.AddField(
            model_name='pdfcontentitem',
            name='slide_display_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Number of seconds to display each slide.'),
        ),
    ]
