# Generated by Django 5.0.6 on 2024-05-20 14:03

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='If left blank, the content item is immediately valid.', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='If left blank, the content item never expires.', null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds')),
                ('display_seconds', models.PositiveIntegerField(default=30, help_text='Seconds to display content item.')),
                ('font_family', models.CharField(blank=True, help_text='Font name to override standard font. Must be installed on display.', max_length=200, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField(blank=True, help_text='If left blank, the playlist is immediately valid.', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='If left blank, the playlist never expires.', null=True)),
                ('content_items', sortedm2m.fields.SortedManyToManyField(help_text=None, to='tvdisplay.contentitem')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('playlists', sortedm2m.fields.SortedManyToManyField(help_text=None, to='tvdisplay.playlist')),
            ],
        ),
    ]
