# Generated by Django 5.0.6 on 2024-05-20 14:54

import infokyllti.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvdisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=infokyllti.storage_backends.PrivateMediaStorage(), upload_to='backgrounds'),
        ),
    ]