# Generated by Django 5.0.6 on 2024-06-02 22:41

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvdisplay', '0002_alter_contentitem_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='playlists',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='tvdisplay.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='content_items',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='tvdisplay.contentitem'),
        ),
    ]
