# Generated by Django 5.0.6 on 2024-06-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvdisplay', '0003_alter_display_playlists_alter_playlist_content_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='online',
        ),
    ]
