# Generated by Django 5.0.12 on 2025-06-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvdisplay', '0004_remove_display_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='override',
            field=models.BooleanField(default=False, help_text='If ticked, this playlist, when assigned and valid, will override any other playlist for that display.'),
        ),
    ]
